src=cat.go       chmod.go  complete.go  du.go   kerberos.go  main.go   mv.go     put.go  touch.go checksum.go  chown.go  df.go        get.go  ls.go        mkdir.go  paths.go  rm.go   util.go
hdfs: $(src)
	go build -ldflags="-s -w"
